apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementPolicy
metadata:
  name: productpage
  labels:
    app: productpage
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    name: productpage
    servicekind: CacheService
spec:
  clusterReplicas: {{ .Values.replicaCount }}  
  clusterLabels:
    matchLabels:
{{ toYaml .Values.targetCluster.labelSelector.matchLabels | indent 6 }}
  resourceHints:
{{ toYaml .Values.targetCluster.resourceSelector | indent 4 }}
