apiVersion: multicluster.istio.io/v1alpha1
kind: ServiceExpositionPolicy
metadata:
  name: reviews-v1
  labels:
    app: reviews
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    name: reviews
spec:
  exposed:
  - name: reviews-v1
    port: 9080

    alias: reviews-v1
    subset: v1
    clusters:
    - cluster1
