{{- if .Values.istio.enabled }}
{{- if .Values.istio.rbac.enabled }}
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-{{ .Values.RatingsLabel }}-viewer
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    chart-use: once
    app: {{ .Chart.Name }}
spec:
  subjects:
  - user: "cluster.local/ns/{{ .Release.Namespace }}/sa/{{ .Chart.Name }}-sa"
  roleRef:
    kind: ServiceRole
    name: "{{ .Values.RatingsLabel }}-viewer"
{{- end }}
{{- end }}
