{{- if .Values.istio.enabled }}
{{- if .Values.istio.rbac.enabled }}
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: {{ .Values.RatingsLabel }}-viewer
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    chart-use: once
    app: {{ .Chart.Name }}
spec:
  rules:
  - services: ["{{ .Values.RatingsLabel }}.{{ .Release.Namespace }}.svc.cluster.local"]
    methods: ["GET"]
{{- end }}
{{- end }}
