apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementPolicy
metadata:
  name: details
  labels:
    app: details
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    name: details
    servicekind: CacheService
spec:
  replicas: {{ .Values.replicaCount }}  
  clusterSelector:
    matchLabels:
{{ toYaml .Values.targetCluster.labelSelector.matchLabels | indent 6 }}
  resourceSelector:
{{ toYaml .Values.targetCluster.resourceSelector | indent 4 }}
