apiVersion: mcm.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: reviews
  labels:
    app: reviews
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    name: reviews
    servicekind: ApplicationService
spec:
  deployer:
    kind: helm
    helm:
      chartURL: https://raw.githubusercontent.com/kalantar/bookinfo-app/master/helm-repo/reviews-0.1.0.tgz
      namespace: {{ .Values.targetClusterNamespace }}
