# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

istio:
  enabled: true
  rbac:
    enabled: false
network:
  enforced: false

replicaCount: 1

targetClusterNamespace: bookinfo
targetCluster:
  labelSelector:
    matchLabels:
      name: owl
  resourceSelector:
    type: cpu
