apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: productpage
  labels:
    app: productpage
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    name: productpage
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        app: productpage
        image: "{{ .Values.image.tag }}"
    spec:
      serviceAccountName: productpage-sa
      containers:
      - name: productpage
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.servicePort }}
{{- if .Values.istio.enabled }}
{{- else }}
        readinessProbe:
          httpGet:
            path: /productpage/health
            port: 9080
          initialDelaySeconds: 20
{{- end }}
        resources:
          requests:
            cpu: "{{ .Values.image.resources.requests.cpu }}"
            memory: "{{ .Values.image.resources.requests.memory }}"
