{{- if .Values.istio.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: productpage-sa
  labels:
    app: productpage
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    name: productpage-sa
    chart-use: once
{{- end }}
