{{- if .Values.istio.enabled }}
{{- if .Values.istio.rbac.enabled }}
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: productpage-viewer
  labels:
    app: {{ .Values.BookInfoLabel }}
spec:
  rules:
  - services: ["productpage.{{ .Release.Namespace }}.svc.cluster.local"]
    methods: ["GET"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-productpage-viewer
  labels:
    app: {{ .Values.BookInfoLabel }}
spec:
  subjects:
  - user: "*"
  roleRef:
    kind: ServiceRole
    name: "productpage-viewer"
{{- end }}
{{- end }}
