apiVersion: mcm.ibm.com/v1alpha1
kind: Application
metadata:
  name: bookinfo
  labels:
    app: bookinfo
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "-" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    name: bookinfo
  spec:
    selector:
      matchExpressions:
      - key: app
        operator: In
        values:
        - productpage
        - details
  componentKinds:
  - group: core
    kind: Pod
