apiVersion: mcm.ibm.com/v1alpha1
kind: ApplicationRelationship
metadata:
    name: productpage-to-details
    labels:
      app: bookinfo
      chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      name: productpage-to-details
      chart-use: once
spec:
  type: usesCreated
  source: 
    kind: Deployable
    name: productpage
  destination: 
    kind: Deployable
    name: details
